-- TASK 1 (BD - TRIO)
-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 09:01:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lojinha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lojinha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lojinha` DEFAULT CHARACTER SET utf8 ;
USE `lojinha` ;

-- -----------------------------------------------------
-- Table `lojinha`.`Funcionários`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojinha`.`Funcionários` (
  `idFuncionários` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idFuncionários`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lojinha`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojinha`.`Clientes` (
  `idClientes` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lojinha`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojinha`.`Telefone` (
  `idTelefone` INT NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `Funcionários_idFuncionários` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idTelefone`, `Funcionários_idFuncionários`, `Clientes_idClientes`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  INDEX `fk_Telefone_Funcionários_idx` (`Funcionários_idFuncionários` ASC) VISIBLE,
  INDEX `fk_Telefone_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Telefone_Funcionários`
    FOREIGN KEY (`Funcionários_idFuncionários`)
    REFERENCES `lojinha`.`Funcionários` (`idFuncionários`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Telefone_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `lojinha`.`Clientes` (`idClientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lojinha`.`Fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojinha`.`Fornecedores` (
  `idFornecedores` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFornecedores`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lojinha`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojinha`.`Endereco` (
  `cidade` VARCHAR(40) NOT NULL,
  `bairro` VARCHAR(40) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Fornecedores_idFornecedores` INT NOT NULL,
  `Funcionários_idFuncionários` INT NOT NULL,
  PRIMARY KEY (`Clientes_idClientes`, `Fornecedores_idFornecedores`, `Funcionários_idFuncionários`),
  INDEX `fk_Endereco_Fornecedores1_idx` (`Fornecedores_idFornecedores` ASC) VISIBLE,
  INDEX `fk_Endereco_Funcionários1_idx` (`Funcionários_idFuncionários` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `lojinha`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Endereco_Fornecedores1`
    FOREIGN KEY (`Fornecedores_idFornecedores`)
    REFERENCES `lojinha`.`Fornecedores` (`idFornecedores`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Endereco_Funcionários1`
    FOREIGN KEY (`Funcionários_idFuncionários`)
    REFERENCES `lojinha`.`Funcionários` (`idFuncionários`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lojinha`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojinha`.`Produtos` (
  `idProdutos` INT NOT NULL,
  `promocao` DECIMAL(5,2) NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `tamanho` VARCHAR(3) NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `Fornecedores_idFornecedores` INT NOT NULL,
  PRIMARY KEY (`idProdutos`, `Fornecedores_idFornecedores`),
  INDEX `fk_Produtos_Fornecedores1_idx` (`Fornecedores_idFornecedores` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_Fornecedores1`
    FOREIGN KEY (`Fornecedores_idFornecedores`)
    REFERENCES `lojinha`.`Fornecedores` (`idFornecedores`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lojinha`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojinha`.`Categorias` (
  `idCategorias` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  PRIMARY KEY (`idCategorias`, `Produtos_idProdutos`),
  INDEX `fk_Categorias_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  CONSTRAINT `fk_Categorias_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `lojinha`.`Produtos` (`idProdutos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lojinha`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojinha`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `localizacao` VARCHAR(25) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `dataSaida` DATETIME NOT NULL,
  `dataEntrada` DATETIME NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  PRIMARY KEY (`idEstoque`, `Produtos_idProdutos`),
  INDEX `fk_Estoque_Produtos1_idx` (`Produtos_idProdutos` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `lojinha`.`Produtos` (`idProdutos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `lojinha`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojinha`.`Venda` (
  `idVenda` INT NOT NULL,
  `valorTotal` DECIMAL(6,2) NOT NULL,
  `formaPag` VARCHAR(25) NOT NULL,
  `data` DATETIME NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  `Produtos_Fornecedores_idFornecedores` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Funcionários_idFuncionários` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `Produtos_idProdutos`, `Produtos_Fornecedores_idFornecedores`, `Clientes_idClientes`, `Funcionários_idFuncionários`),
  INDEX `fk_Venda_Produtos1_idx` (`Produtos_idProdutos` ASC, `Produtos_Fornecedores_idFornecedores` ASC) VISIBLE,
  INDEX `fk_Venda_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Venda_Funcionários1_idx` (`Funcionários_idFuncionários` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos` , `Produtos_Fornecedores_idFornecedores`)
    REFERENCES `lojinha`.`Produtos` (`idProdutos` , `Fornecedores_idFornecedores`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venda_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `lojinha`.`Clientes` (`idClientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venda_Funcionários1`
    FOREIGN KEY (`Funcionários_idFuncionários`)
    REFERENCES `lojinha`.`Funcionários` (`idFuncionários`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;